spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:places}"
    username: "${MYSQL_USERNAME:springuser}"
    password: "${MYSQL_PASSWORD:Spring123.}"
  jpa:
    hibernate:
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
